"""
Install wnframework and port
"""

import sys, os

# settings

from install_settings import *

def make_defs():
	os.system('cp %s %s' % (os.path.join('wnframework','cgi-bin','defs_template.py'), os.path.join('wnframework','cgi-bin','defs.py')))

	# ask for the user password
	if not db_password:
		db_password = raw_input('Password of the new database:')

	defs_content = open(os.path.join('wnframework','cgi-bin','defs.py'), 'r').readlines()
	defs = open(os.path.join('wnframework','cgi-bin','defs.py'), 'w')
	
	# replace the line that begins with db_password with the new password
	for d in defs_content:
		if d.startswith('db_password'):
			defs.write('db_password="%s"\n' % db_password.replace('"', '\"'))
		else:
			defs.write(d+'\n')

	defs.close()

def restore_db():
	"""
		import the database
	"""
	sys.path.append(os.path.join('wnframework','cgi-bin'))

	import webnotes
	from webnotes.db import Database
	from webnotes.install_lib.install import Installer

	new_db_name = raw_input('Name of the new database (default: %s):' % db_name)
	root_password = raw_input('Root password for mysql (for db and user creation):')
	if new_db_name:
		db_name = new_db_name

	inst = Installer(root_password)

	# unzip
	os.system("gunzip %s" % os.path.join('erpnext', 'master.sql.gz'))

	# import
	inst.import_from_db(new_db_name or db_name, os.path.join('erpnext', 'master.sql')

	# cleanup
	webnotes.conn = Database('localhost','root',root_password)
	webnotes.conn.use(new_db_name or db_name)
	webnotes.conn.set_value('Control Panel',None,'company_name',raw_input('[ERPNext setup] Enter the name of the full name of your company:'))
	webnotes.conn.set_value('Control Panel',None,'sync_with_gateway', None)

	# copy icons
	if not os.path.exists(os.path.join('wnframework','images','user')):
		os.mkdir(os.path.join('wnframework','images','user'))
	os.system("cp %s %s", os.path.join('erpnext','module_icons.png'),os.path.join('wnframework','images','user'))

def setup_httpd():
	conf = """
# generated by erpnext install.py
<VirtualHost *:%(port)s>
	# set directory root
	DirectoryRoot %(directory_root)s

	# allow cgi execution in the app
	Options +ExecCGI
	AddHandler cgi-script .cgi
	
	# default index is .cgi
	DirectoryIndex index.cgi

	# dont show .py files
	RewriteEngine On
	RewriteRule .py [F]

	Order Allow, Deny
	Allow From All

</VirtualHost>
	"""

	if os.path.exists(os.path.join('etc','httpd','conf.d')):
		c = open(os.path.join('etc','httpd','conf.d','erpnext.conf','w'))

	elif os.path.exists(os.path.join('etc','apache2','conf.d')):
		c = open(os.path.join('etc','httpd','apache2','erpnext.conf','w'))

	else:
		"[Error] Could not find apache config files in the usual places, please manually add the erpnext.conf file in your apache conf folder"
		c = open('erpnext.con', 'w')

	c.write(conf % {'port': http_port, 'directory_root': so.path.abspath('wnframework')})
	c.close()


def install():
	make_defs()
	restore_db()
	setup_httpd()

	print "Install complete. Please restart your http server and go to http://localhost:%s on your browser to start erpnext" % http_port


if __name__=='__main__':
	install()



